### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by nkev** [eReuse/devicehub-teal#1]
Firstly, I love your [article](https://www.bustawin.com/dags-with-materialized-paths-using-postgres-ltree/) on multi-parent ltree implementations!

Please note broken link:
![image](https://user-images.githubusercontent.com/5410916/53457805-b305ab80-3a87-11e9-80a1-1652e40f66a6.png)

Also, if you're not already onto it, I would highly recommend replacing Flask (which is great!) with Go.

Happy coding!

**Comment by bustawin** [comment]
Thank you for the kind commends and for finding the typo, I will definitely change it. Here is the URL that should have been in there: https://github.com/ereuse/teal.

**Comment by nkev** [comment]
Re. your question in the article about removing the PK in the path table, how about something like this:

```SQL
	 -- Delete without the ID in the path table            
	DELETE FROM path T1 USING path T2
	WHERE T1.ctid < T2.ctid  -- delete the "older" ones using Postgres internal ID
	  AND T1.lot_id = T2.lot_id -- list columns that define duplicates
	  AND T1.path = T2.path;
```
