### ISSUE TITLE
batch POST /proofs with type ProofTransfer fails

### ISSUE THREAD

**Issue by forste** [eReuse/devicehub-teal#12]
Just tried the E2E transfer with deliverynote. It works until last step of batch POSTing to /proofs

**Client**:
- Branch: https://github.com/eReuse/DeviceHubClient/tree/proofs.register-device-address
- Commit: https://github.com/eReuse/DeviceHubClient/commit/5066a69cec48fbbfdb0f0c53d5a8beade0f0485f

**Server**:
- Branch: Probably https://github.com/eReuse/devicehub-teal/tree/mvp_proof
- Commit: ?

**API ENDPOINT**
POST https://api.dh.usody.net/dbtest/proofs/

**PAYLOAD**

`{"proofs":[{"type":"ProofTransfer","ethereumHash":"0x5466c4d125f43d180fb5013aa35ab190a6a103af357b584ac5111333cea2eacb","deviceID":129,"supplier":{"created":"2020-03-19T01:08:29.011317+00:00","email":"user2@dhub.com","ethereum_address":"0x56EbFdbAA98f52027A9776456e4fcD5d91090818","id":"b455e426-db02-4a98-885a-728e14db1cdc","token":"NTY2MzVhY2EtOGIyMC00YTVlLWFmN2YtOWZhZjY3NTM4ZjgzOg==","type":"User","updated":"2020-03-19T01:08:28.975892+00:00"},"receiver":{"created":"2020-03-19T01:08:28.910772+00:00","email":"user@dhub.com","ethereum_address":"0xC79F7fE80B5676fe38D8187b79d55F7A61e702b2","id":"0ad0e875-8c93-4b6e-962a-64de9c17662b","token":"NjlhYmRjNWEtMzAyYi00MzQ0LWJjY2QtYjIxMDhkMzJlMzAzOg==","type":"User","updated":"2020-03-19T01:08:28.908657+00:00"},"deposit":10},{"type":"ProofTransfer","ethereumHash":"0xf13dc06c77c2e65eb2c347b251ae2cbaa62ee13121e3c432551fb122411980d2","deviceID":119,"supplier":{"created":"2020-03-19T01:08:29.011317+00:00","email":"user2@dhub.com","ethereum_address":"0x56EbFdbAA98f52027A9776456e4fcD5d91090818","id":"b455e426-db02-4a98-885a-728e14db1cdc","token":"NTY2MzVhY2EtOGIyMC00YTVlLWFmN2YtOWZhZjY3NTM4ZjgzOg==","type":"User","updated":"2020-03-19T01:08:28.975892+00:00"},"receiver":{"created":"2020-03-19T01:08:28.910772+00:00","email":"user@dhub.com","ethereum_address":"0xC79F7fE80B5676fe38D8187b79d55F7A61e702b2","id":"0ad0e875-8c93-4b6e-962a-64de9c17662b","token":"NjlhYmRjNWEtMzAyYi00MzQ0LWJjY2QtYjIxMDhkMzJlMzAzOg==","type":"User","updated":"2020-03-19T01:08:28.908657+00:00"},"deposit":10}],"batch":true}`

**RESPONSE**

`{"code":422,"message":{"deviceIDs":["Missing data for required field."],"transferID":["Missing data for required field."]},"type":"ValidationError"}`

**Comment by fedjo** [comment]
Is the ```ProofTransfer``` supposed to have a ```supplier``` and ```receiver``` ?

I couldn't find this on the specification doc.

https://pad.dyne.org/code/#/2/code/edit/sp3LgKNHppnyzakS0hZSrQK9/

**Comment by forste** [comment]
For the POST to `/proofs` for type `ProofTransfer` and its properties `supplier `and `receiver`, please refer to "Chapter 6 - Owner B (=receiver) confirms transfer" of the specs as below:
```
batch: true
proofs: [{
    type: "ProofTransfer" 
    ethereumHash: string // hash of the ethereum addresses of the proof
    deviceID: int 

    "supplier":{"id":"asd123","ethereum_address":"ad1243s"},
    "receiver":{"id":"xasd123","ethereum_address":"acasdads"},
    "deposit":10
  }]
```

**Comment by forste** [comment]
yes, we still need calibration of input data. In general, we should try to stay consistent. For `User `data and in fact any nested entities specifically, I think it's better prefer to store the ID over the ethereum_address, because the ID is the general identifier in the database.

So maybe we can just store e.g. the user ID as userID, so it would be 
```
batch: true
proofs: [{
    type: "ProofTransfer", 
    ethereumHash: string, // hash of the ethereum addresses of the proof
    deviceID: int,

    "supplierID": "asd123", //maybe int?
    "receiverID": "xasd123", //maybe int?
    "deposit":10
  }]
```

**Comment by forste** [comment]
For responses, 201 with plain without details of nested objects is fine!

**Comment by fedjo** [comment]
Cool! Thanks for your recommendations Stephan.
I believe that at this step let's keep the ethereum_address as ID because is also user in the implementation of delivery note as this.

The cost of changing is not big, if we decide to do it in the second iteration

**Comment by forste** [comment]
okay, please discuss this also with @emmdim 

In any case, I have created a separate issue for this https://github.com/eReuse/devicehub-teal/issues/14

**Comment by fedjo** [comment]
Changes for ```ProofTransfer```, currently using ```ethereum_address``` as ```supplierID```, ```receiverID```

**Comment by emmdim** [comment]
> I believe that at this step let's keep the ethereum_address as ID because is also user in the implementation of delivery note as this.
The new issue refers to a future iteration. Also relates to Deliverynotes and Lots.
So yes, for now let's keep it like that.

**Comment by forste** [comment]
Hi,

just tested new code from @fedjo (commit https://github.com/eReuse/devicehub-teal/commit/bd2d72ad69956b7c96595402ba40520d22971b97).

Still getting a 400 error (errors.ForeignKeyViolation)

**PAYLOAD**

```
{"proofs":[{"type":"ProofTransfer","ethereumHash":"0x121f6bdfaa1c26a0e2f5d98c0e41feb7880e13b6b39aaaba078d4d0aea1cf80b","deviceID":129,"supplierID":"bfdb6acd-6ec6-493a-b621-0629badbbb63","receiverID":"f765b6cd-4d2d-46b7-9b4b-9cc909e31096","deposit":15},{"type":"ProofTransfer","ethereumHash":"0x5523bab6fbda420b0324615ecc7cc7500493d7a2766b46b6945560d6b38a2c48","deviceID":103,"supplierID":"bfdb6acd-6ec6-493a-b621-0629badbbb63","receiverID":"f765b6cd-4d2d-46b7-9b4b-9cc909e31096","deposit":15},{"type":"ProofTransfer","ethereumHash":"0x644c76a2dc620fb7b68980093b2571d3d24cb0b83c9051653e4c3b2062a2f1de","deviceID":70,"supplierID":"bfdb6acd-6ec6-493a-b621-0629badbbb63","receiverID":"f765b6cd-4d2d-46b7-9b4b-9cc909e31096","deposit":15}],"batch":true}
```

RESPONSE

```
{"code":400,"message":"(psycopg2.errors.ForeignKeyViolation) insert or update on table \"proof_transfer\" violates foreign key constraint \"proof_transfer_supplier_id_fkey\"\nDETAIL:  Key (supplier_id)=(bfdb6acd-6ec6-493a-b621-0629badbbb63) is not present in table \"user\".\n [SQL: 'INSERT INTO proof_transfer (supplier_id, receiver_id, deposit, id) VALUES (%(supplier_id)s, %(receiver_id)s, %(deposit)s, %(id)s)'] [parameters: {'supplier_id': 'bfdb6acd-6ec6-493a-b621-0629badbbb63', 'receiver_id': 'f765b6cd-4d2d-46b7-9b4b-9cc909e31096', 'deposit': 15, 'id': UUID('4724316b-005a-44ee-8cd2-3cf1f06ec7a3')}] (Background on this error at: http://sqlalche.me/e/gkpj)","type":"DBError"}

```

**Comment by forste** [comment]
the supplier_id in the payload should be fine. no idea what's causing the issue here.

@emmdim and @fedjo can you test this exact JSON payload and find out the problem?

**Comment by fedjo** [comment]
Sure will give a try.

Can you elaborate a little bit on the constraint for the ```supplier``` (and maybe potentially the ```receiver```) ?

Thanks

**Comment by forste** [comment]
just tried it with the deployment made and it works!!
