### ISSUE TITLE
Change FOREIGN keys to use entity.id instead of entity.ethereum_address 

### ISSUE THREAD

**Issue by forste** [eReuse/devicehub-teal#14]
E.g. the relation owner between device and user:

now

`device.owner_address is a FOREIGN KEY on user.ethereum_address`

better would be

`device.owner_id is a FOREIGN KEY on user.id`

**Comment by fedjo** [comment]
I change the for ```supplier```, ```proof_author``` and ```receiver``` for all Proofs to a FOREIGN key to ```entity.id```

Please try POSTing some Proofs to confirm that the API is working.

Once ```POST /proofs/``` works I will update the FOREIGN keys for ```DeliveryNote``` as well

**Comment by fedjo** [comment]
I used the following JSON.
```json
{
  "proofs": [
    {
      "type": "ProofDataWipe",
      "ethereumHash": "0xa6c2e1f312b0fd37b47b6e66b195bdce8a734c50e811a23581d7b1b1ea0bf3d0",
      "deviceID": 129,
      "date": "2018-07-11T11:20:01.004Z",
      "result": true,
      "proofAuthor": "44793fa7-94e9-4cc4-8353-5582292838b1",
      "erasureID": "2125b249-3e4a-45be-9d7f-c314d810ccbb"
    },
    {
      "type": "ProofDataWipe",
      "ethereumHash": "0x5882e7d0023491aed09d0604c406c9be9217637b6ff7c086081bb87649c8144a",
      "deviceID": 103,
      "date": "2018-07-11T10:49:31.998Z",
      "result": true,
      "proofAuthor": "44793fa7-94e9-4cc4-8353-5582292838b1",
      "erasureID": "2125b249-3e4a-45be-9d7f-c314d810ccbb"
    }
  ],
  "batch": true
}
```

**Comment by forste** [comment]
@emmdim, have you already updated the testing server with the newest changes from @fedjo?

Just tried the POST the ProofDataWipe, still failing even though the JSON data types match the ones you mentioned using exactly. I suppose that your code is not deployed yet. I'm documenting this issue here: https://github.com/eReuse/devicehub-teal/issues/18

**Comment by forste** [comment]
> 
> 
> I used the following JSON.
> 
> ```json
> {
>   "proofs": [
>     {
>       "type": "ProofDataWipe",
>       "ethereumHash": "0xa6c2e1f312b0fd37b47b6e66b195bdce8a734c50e811a23581d7b1b1ea0bf3d0",
>       "deviceID": 129,
>       "date": "2018-07-11T11:20:01.004Z",
>       "result": true,
>       "proofAuthor": "44793fa7-94e9-4cc4-8353-5582292838b1",
>       "erasureID": "2125b249-3e4a-45be-9d7f-c314d810ccbb"
>     },
>     {
>       "type": "ProofDataWipe",
>       "ethereumHash": "0x5882e7d0023491aed09d0604c406c9be9217637b6ff7c086081bb87649c8144a",
>       "deviceID": 103,
>       "date": "2018-07-11T10:49:31.998Z",
>       "result": true,
>       "proofAuthor": "44793fa7-94e9-4cc4-8353-5582292838b1",
>       "erasureID": "2125b249-3e4a-45be-9d7f-c314d810ccbb"
>     }
>   ],
>   "batch": true
> }
> ```

Just tried the POST the ProofDataWipe, still failing even though the JSON data types match the ones you mentioned using exactly. I suppose that your code is not deployed yet. I'm documenting this issue here: #18

**Comment by fedjo** [comment]
Yeah, I committed quite late yesterday so I supposed the new code has not been deployed.

In any case this is the data structure that I used for testing.

Does this format sounds good @forste ?

**Comment by forste** [comment]
Yes, this format should work now. Thanks!

**Comment by forste** [comment]
so, as mentioned in https://github.com/eReuse/devicehub-teal/issues/18 and https://github.com/eReuse/devicehub-teal/issues/12, for the proofs this works!

**Comment by forste** [comment]
not sure, if any other changes need to be made for this? If not, we can close this issue as well

**Comment by forste** [comment]
also should `Computer.owner_address`, and `Computer.receiver_address` should be replaced with `owner_id` and `receiver_id` respectively

**Comment by fedjo** [comment]
Cool. So far I keep noted changes for ```Deliverynote``` and ```Computer``` fields.

I will soon proceed with the changes.

I suggest, let's keep the issue open, until we complete all the necessary changes to all the FOREIGN keys.

**Comment by forste** [comment]
Also `Lot.owner_address` should be `Lot.owner_id`

https://github.com/eReuse/devicehub-teal/blob/bc69d194f4040e0630095de88f7ca5d8b6b8ed48/ereuse_devicehub/resources/lot/schemas.py#L25
