### ISSUE TITLE
Error message when adding a device I no longer own to a temporary lot

### ISSUE THREAD

**Issue by dfranquesa** [eReuse/devicehub-teal#164]
When I add a device that I no longer own to a temporary lot/batch I get the message ":-) Done" but I should get another message saying "This operation is not possible. This device is no longer in your inventory". 
The behaviour is correct because it does not appear in the temporary batch but the message I get is confusion.

To reproduce this bug you can go to the public account hello@usody.com and add the device "Laptop Lenovo 7434ah9" with ID "3OAOW" to a temporally lot, i.e "Test1". This device is in lote "Donation 5".

**Comment by slamora** [comment]
Closing because seems that is issue is related to deprecated [angular client](https://github.com/eReuse/DeviceHubClient), isnt'it?
