### ISSUE TITLE
batch POST /proofs with type 'ProofDataWipe' fails

### ISSUE THREAD

**Issue by forste** [eReuse/devicehub-teal#18]
Just tried again POSTing a few ProofDataWipe proofs

**ENVIRONMENT**
Client
- Branch: https://github.com/eReuse/DeviceHubClient/tree/proofs
- Commit: https://github.com/eReuse/DeviceHubClient/commit/701f1edecdf26c6d9dbf737a952932a90b083b63

Server:
- Branch: https://github.com/eReuse/devicehub-teal/tree/mvp_proof
- Commit: @emmdim which commit is deployed at the moment?

**PAYLOAD**

```
{"proofs":[{"type":"ProofDataWipe","ethereumHash":"0x79046ae7eb08f55d834a32db34b466f39de757f117bdf85560ab3e9931e65d74","deviceID":129,"date":"2018-07-11T11:20:01.004Z","result":true,"proofAuthor":"0xC79F7fE80B5676fe38D8187b79d55F7A61e702b2","erasureID":"655331bd-2c53-41b3-a2ac-37526c5cff04"},{"type":"ProofDataWipe","ethereumHash":"0xc1765abf8b51980c64a35e3ca298622fe141483c004b86177dcb372e6e8249d2","deviceID":103,"date":"2018-07-11T10:49:31.998Z","result":true,"proofAuthor":"0xC79F7fE80B5676fe38D8187b79d55F7A61e702b2","erasureID":"5dee2003-906c-4b9f-9773-9f70b21a7a54"}],"batch":true}
```

**RESPONSE**

`{"code":500,"message":"%d format: a number is required, not str","type":"TypeError"}`

**Comment by fedjo** [comment]
Good morning!

Please have a look on #14

**Comment by forste** [comment]
Just tested commit https://github.com/eReuse/devicehub-teal/commit/bd2d72ad69956b7c96595402ba40520d22971b97

Still getting the same error as above 

`{"code":500,"message":"%d format: a number is required, not str","type":"TypeError"}`

**Comment by fedjo** [comment]
Are you using the payload from issue #14 ?

**Comment by fedjo** [comment]
Just tried locally, and ```ProofDataWipe``` seem to work for the payload posted on #14

As mentioned [here](https://github.com/eReuse/devicehub-teal/issues/14#issuecomment-603518500) ```supplier```, ```receiver``` and ```proof_author``` are referenced by the UUID and not the ethereum_hash address.

**Comment by forste** [comment]
> 
> 
> Are you using the payload from issue #14 ?

Yes. I have updated the payload in the comment above

**Comment by forste** [comment]
> 
> 
> Just tried locally, and `ProofDataWipe` seem to work for the payload posted on #14
> 
> As mentioned [here](https://github.com/eReuse/devicehub-teal/issues/14#issuecomment-603518500) `supplier`, `receiver` and `proof_author` are referenced by the UUID and not the ethereum_hash address.

OK, let me double check the payload again...

**Comment by forste** [comment]
Checked the payload, it matches this one https://github.com/eReuse/devicehub-teal/issues/14#issuecomment-603519127

**Comment by fedjo** [comment]
OK. Could it be that the database is not updated with latest models changes?

**Comment by forste** [comment]
seems so. DB was wiped when I checked

**Comment by forste** [comment]
> 
> 
> Just tried locally, and `ProofDataWipe` seem to work for the payload posted on #14
> 
> As mentioned [here](https://github.com/eReuse/devicehub-teal/issues/14#issuecomment-603518500) `supplier`, `receiver` and `proof_author` are referenced by the UUID and not the ethereum_hash address.

Just checked again, and realized I had not changed `proof_author` to use the ID instead of address. Let me check how we can resolve this

**Comment by forste** [comment]
we need to change the `data_key` from `proofAuthor` to `proofAuthorID`, is this possible?

the reason is that the blockchain needs the `proofAuthor` value to be an ethereum_address

**Comment by fedjo** [comment]
> we need to change the `data_key` from `proofAuthor` to `proofAuthorID`, is this possible?
> 
> the reason is that the blockchain needs the `proofAuthor` value to be an ethereum_address

Cool no problem, I change it immediately

**Comment by fedjo** [comment]
@forste 
Can you give it a try now, once that @emmdim re-deployed changes for ```proofAuthorID``` ?

**Comment by forste** [comment]
just tried and it works!!! amazing!
