### ISSUE TITLE
Return diskUsage and algorithmVersion properties in response to GET /devices

### ISSUE THREAD

**Issue by forste** [eReuse/devicehub-teal#19]
ProofFunction needs `diskUsage` and `algorithmVersion` (= version of rating algorithm) but this property is not returned by server

**Comment by fedjo** [comment]
Is ```algorithmVersion``` intended to be saved to the database as well?

Because on [Specs Chapter 7.3 Proof of function](https://pad.dyne.org/code/#/2/code/edit/sp3LgKNHppnyzakS0hZSrQK9/) , ```algorithmVersion``` is only provided in the request  to **web3.service**

**Comment by fedjo** [comment]
Hi @forste ,

Can you please give an example of the current response of GET /devices ?

Thanks

**Comment by forste** [comment]
Sure @fedjo, please find it here: https://pad.dyne.org/code/#/2/code/edit/K9ErPCuAt5QlpduytoC5mm50/

**Comment by forste** [comment]
@JNadeu might know how to get this data on the server, can you give us some advice?

**Comment by JNadeu** [comment]
Yes, in the case of diskUsage, there are a data that we collect in cases where the Workbench runs the SMART test on the hard drive. In Resources -> Actions -> models -> class TestDataStorage -> var lifetime = Column(Interval)

In the other case of algorithmVersion, in Resources -> Actions -> models -> class Rate & class Price -> var version = Column(StrictVersionType)

**Comment by forste** [comment]
ok, I see in the sample response that the TestDataStorage.lifetime is actually already returned. @JNadeu, do you know which unit it is in? the documentation is not clear about this http://devicehub.ereuse.org/actions.html#dh-testdatastorage

**Comment by forste** [comment]
@JNadeu what about algorithmVersion for the rating, is this stored somewhere?

**Comment by JNadeu** [comment]
> ok, I see in the sample response (https://pad.dyne.org/code/#/2/code/edit/K9ErPCuAt5QlpduytoC5mm50/) that the TestDataStorage.lifetime is actually already returned. @JNadeu, do you know which unit it is in? the documentation is not clear about this http://devicehub.ereuse.org/actions.html#dh-testdatastorage

On Resources/Actions/schemas.py -> inside TestDataStorage class -> lifetime = TimeDelta(precision=TimeDelta.HOURS)

**Comment by JNadeu** [comment]
> @JNadeu what about algorithmVersion for the rating, is this stored somewhere?

Inside Actions there are Rate.version and also a Price.version

But at the moment we are not assigning any value to this variable. Since we only have a current rate version and although the system was going to focus to use several versions, if we made some small adaptations for this purpose but if I remember correctly we need to finish it well.

**Comment by forste** [comment]
> 
> 
> > @JNadeu what about algorithmVersion for the rating, is this stored somewhere?
> 
> Inside Actions there are Rate.version and also a Price.version
> 
> But at the moment we are not assigning any value to this variable. Since we only have a current rate version and although the system was going to focus to use several versions, if we made some small adaptations for this purpose but if I remember correctly we need to finish it well.

ok, the `algorithmVersion ` property is for now determined client-side then

**Comment by forste** [comment]
> 
> 
> > ok, I see in the sample response (https://pad.dyne.org/code/#/2/code/edit/K9ErPCuAt5QlpduytoC5mm50/) that the TestDataStorage.lifetime is actually already returned. @JNadeu, do you know which unit it is in? the documentation is not clear about this http://devicehub.ereuse.org/actions.html#dh-testdatastorage
> 
> On Resources/Actions/schemas.py -> inside TestDataStorage class -> lifetime = TimeDelta(precision=TimeDelta.HOURS)

Thanks, so hours used. Perfect, client will use this property then
