### ISSUE TITLE
Return proofs in response to GET /devices

### ISSUE THREAD

**Issue by forste** [eReuse/devicehub-teal#20]
Every device returned in response to GET /devices should have its associated proofs as an [Proof] array assigned to `device.proofs`. Proofs should contain full nested data, especially supplier and receiver data

**Comment by fedjo** [comment]
Currently only ```ProofTransfer``` and ```ProofReuse``` have ```supplier``` and ```receiver``` fields

**Comment by forste** [comment]
I talked with @emmdim about this. We still have to decide on some issues. Let's leave it closed for now and reopen when needed
