### ISSUE TITLE
POST /proofs ProofReuse: Make properties receiver_id and supplier_id optional

### ISSUE THREAD

**Issue by forste** [eReuse/devicehub-teal#21]
@fedjo, we do not have access to neither `receiver_id` nor `supplier_id` properties on the client, so we can not pass it to POST /proofs for ProofReuse. It will take some time until we figure out how/if the client gets this data

Can you make these two properties optional, or remove them temporarily?

**Comment by fedjo** [comment]
The fields became optional in the database model and it schema.
With this commit,    a re-deploy is required as well as an update on the db models.

@forste @emmdim

**Comment by forste** [comment]
thanks @fedjo 

@emmdim, please let me know, when this is deployed to the testing server

**Comment by forste** [comment]
Just read on riot that the code is already deployed
