### ISSUE TITLE
Limit visibility of lots and devices

### ISSUE THREAD

**Issue by forste** [eReuse/devicehub-teal#22]
Currently, all users can see all deliverynotes, lots and devices. 

We want to limit visibility so that
- generally, devices and lots are only visible to their owner (= the user that created the device)
- additionally, a deliverynote including its associated lot and devices should be visible to both the deliverynote's supplier and receiver independently whether they are owners

For this, the following API endpoints would need adaptions:

- GET /devices to limit visibility of devices
- GET /lots?format=UiTree to limit visibility of lots and deliverynotes

@emmdim @fedjo, is this possible to implement server-side?

**Comment by fedjo** [comment]
Implemented but not merged to **testing** nor **devel**

Branch [feature/22-device-lot-visibility](https://github.com/eReuse/devicehub-teal/tree/feature/22-device-lot-visibility)

**Comment by forste** [comment]
I tested this on April 30 and it worked, so AFAIK this can be merged in to **testing**

**Comment by fedjo** [comment]
That's cool! We are not going to merge (as I understood) as soon as we decide if we really need this feature. 
This is the meaning of *frozen*

**Comment by forste** [comment]
@emmdim @fedjo this feature is really needed. 

I created a pull request to merge it into `testing`: https://github.com/eReuse/devicehub-teal/pull/38
