### ISSUE TITLE
JS error prevents top bar search engine working on some pages

### ISSUE THREAD

**Issue by slamora** [eReuse/devicehub-teal#278]
Cames from [review on #273](https://github.com/eReuse/devicehub-teal/pull/273#pullrequestreview-979781523):

This JS error is raised on the following pages that prevents other JS based features to work (e.g. top bar search engine):
```js
main.js:221 Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
    at main.js:221:50
    at main.js:353:3

// main.js:221
  /**
   * Avoid hide dropdown when user clicked inside
   */
  document.getElementById("dropDownLotsSelector").addEventListener("click", event => {
    event.stopPropagation();
  })
```
- [ ] /inventory/lot/add/
- [ ] /inventory/device/
- [ ] /inventory/upload-snapshot/
- [ ] /inventory/device/add/
- [ ] /labels/print
- [ ] /labels/

**Comment by RubenPX** [comment]
Fixed here --> https://github.com/eReuse/devicehub-teal/pull/273/commits/191539608b2d7d560ddea64676b84e459af13800 in https://github.com/eReuse/devicehub-teal/pull/273
