### ISSUE TITLE
Export on csv file the results of GET /lots/ information

### ISSUE THREAD

**Issue by JNadeu** [eReuse/devicehub-teal#33]
Current branch of the issue: [export-lot-description](https://github.com/eReuse/devicehub-teal/tree/feature/33-export-lot-description)

We have redefined this issue. The general idea is to be able to download a file.csv with information of all the user's lots. 
Headers of csv = [id (uuid), name, description].

My fronts right now are:

1. If we can use the /lots/ GET to get a json with the information about a user's lots. But we still have to create a new endpoint to download the csv file?
2. Transform the json from the previous point into a csv that can be downloaded by performing a GET (to for example '/documents/lots/')

In general I'm having a hard time implementing this feature properly. @fedjo Any idea where to begin?

**Comment by emmdim** [comment]
Hey everyone, let's discuss here: https://github.com/eReuse/devicehub-teal/pull/34/files
