### ISSUE TITLE
Scan QR named tag redirect to 405 Method Not Allowed

### ISSUE THREAD

**Issue by JNadeu** [eReuse/devicehub-teal#51]
To recreate the procedure:
1. A named tag is created.
2. This named tag is assigned to a device (Computer).
3. The named tag is printed, generating a QR and the QR is scanned.

The expected result would be the opening of the public link.

The current result is that it redirects you to a 405 Method Not Allowed.

**Comment by cayop** [comment]
This was fixed adding new entries to DNS
