### ISSUE TITLE
#1857 Bug: Accepting SMART results even if the hard drive state is deplorable

### ISSUE THREAD

**Issue by JNadeu** [eReuse/devicehub-teal#67]
There are cases where the SMART gives really horrible hard disk status results, and these results are saved as a SmallInt variable and the range of the variable type is exceeded. A smallint can have a maximum value of 32767. Specifically we have found examples like the attachment file
[hdd-component.smart-failed.example.json.txt](https://github.com/eReuse/devicehub-teal/files/5384079/hdd-component.smart-failed.example.json.txt) that the fields "offlineUncorrectable": 182042944 and "currentPendingSectorCount": 473302660 exceed it.

The solution I propose is to increase these two variables to Integers:
_current_pending_sector_count = Column(SmallInteger)
offline_uncorrectable = Column(SmallInteger)_

**Comment by cayop** [comment]
Fixed with https://github.com/eReuse/devicehub-teal/pull/110
