### ISSUE TITLE
Improve JSON backup name changing date field in a more understandable way

### ISSUE THREAD

**Issue by JNadeu** [eReuse/devicehub-teal#74]
**Improvements on Issue #61**  

Now when you save a snapshot it comes out with a name similar to the following example:

_'2020-10-21-18-0001-01-01 00:00:00_user@dhub.com_uuid.json'_

A possible solution would be to set the date in this way more or less, 'yyyy-mm-dd-hh:mm:ss':

_'2020-10-21-18:48:22_user@dhub.com_uuid.json'_

**Comment by cayop** [comment]
Fixed in (https://github.com/eReuse/devicehub-teal/pull/81)
