### ISSUE TITLE
#1868 Test end-To-End usody Beta - Merge a device - two snapshots with a device without a serial number

### ISSUE THREAD

**Issue by cayop** [eReuse/devicehub-teal#79]
It's not possible merge 2 devices:

Description: We upload two snapshots of the same device without a serial number and try to merge them.
Error: Merge do not give any result, two snapshots still are there.

Date: 19/10/20

Client: 0.5.0b2
Server: 1.0b
Tags: 1.0b

Test de merge:
user: user@dhub.com

    upload AAAA8-acer-happy.snapshot-noserial-snapshot1.json
    -> ok, it appears in the inventory, Laptop Acer Aohappy, fecha updated 10/19/20

    upload AAAA8-acer-happy.snapshot-noserial-snapshot2.json
    -> ok, it apperars, Snapshot: ⚠ Warning — Workbench 11.0b9

    Select both devices, try merge.
    -> nothing happens

**Comment by JNadeu** [comment]
Information extra about merge two devices, primary device used as a base to add all the info of the secondary device, the endpoint in this case is on testing server:

_POST  https://api.testing.usody.com/usodybeta/devices/<id_primary_device>/merge/<id_secondary_device>_
